app:
  frontUrl: http://localhost:4200
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test;MODE=Postgresql;DATABASE_TO_LOWER=TRUE;
#    url: jdbc:postgresql://localhost:5432/Escolago2
#    username: postgres
#    password: 123
#    driver-class-name: org.postgresql.Driver